version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - PORT=3000
    volumes:
      - ./backend:/usr/src/app
    command: npm run start:backend

  frontend:
    build:
      context: .
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    depends_on:
      - backend